data:
  patch_size: 224
  patch_stride: 224
  tissue_threshold: 0.8   # fraction of non-white pixels for patch keep
model:
  name: resnet18
  num_classes: 2
train:
  epochs: 10
  batch: 32
  lr: 1e-3
inference:
  heatmap_downsample: 8   # larger -> smaller heatmap
